{
  "openapi": "3.0.0",
  "paths": {
    "/person/{id}/diagnostic": {
      "post": {
        "operationId": "CreateController_create",
        "summary": "Cria um objeto DIAGNOSTIC",
        "description": "\n    O que é DIAGNOSTIC?:\n      * DIAGNOSTIC representa o resultado de um exame que pertence ao paciente (person)\n      * O BODY da requisição precisa ter no máximo 6MB de tamanho\n\n    Campo opcional caso deseje enviar arquivos:\n      * result_file: \n          base_64: arquivo no formato base64 com tamanho máximo de 5MB\n          mime_type: tipo do arquivo. EX: image/jpeg, image/png, application/pdf\n    ",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": false,
                "$ref": "#/components/schemas/DiagnosticCreateRequestSchema"
              },
              "examples": {
                "requiredOnly": {
                  "description": "Somente campos obrigatórios. Note que o campo ID segue a regra descrita acima.",
                  "summary": "Somente campos obrigatórios",
                  "value": {
                    "remetent": "Laboratório X",
                    "examination_name": "Hemograma",
                    "examination_date": "2021-08-31T12:24:30.295Z",
                    "result_description": "Resultado negativo"
                  }
                },
                "full": {
                  "summary": "Todos os campos",
                  "description": "Exemplo com todos os campos possíveis",
                  "value": {
                    "remetent": "Laboratório X",
                    "examination_name": "Hemograma",
                    "examination_date": "2021-08-31T12:24:30.295Z",
                    "result_description": "Resultado negativo",
                    "result_file": {
                      "base_64": "9j4AAQSkZJRgABAQEASABIAAD/4QcdRXhpZgAASUkqAAgAAAALAAABBAABAAAAcAgAABABAgAUAAAAkgAAAAEBBAABAAAAQAsAADIBAgAUAAAApgAAABIBAwABAAAAAQAAABMCAwABAAAAAQAAAGmHBAABAAAA0wAAACgBAwABAAAAAgAAABoBBQABAAAAugAAABsBBQABAAAAwgAAAA8BAgAJAAAAygAAAOsGAABtb3Rvcm9sYSBvbmUgdmlzaW9uADIwMjE6MDI6MjUgMTY6MjE6MzQASAAAAAEAAABIAAAAAQAAAG1vdG9yb2xhACQAfJIHALgDAACJAgAAJ4gDAAEAAADdAAAAIogDAAEAAAACAAAAnYIFAAEAAABBBgAAmoIFAAEAAABJBgAAkpICAAUAAABRBgAAkZICAAUAAABWBgAAkJICA",
                      "mime_type": "image/png"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Person successfully created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DiagnosticCreateRequestSchema"
                }
              }
            }
          },
          "400": {
            "description": "Validation Error (field type)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DavHttpExceptionDto"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error (logic)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DavHttpExceptionDto"
                }
              }
            }
          }
        },
        "tags": [
          "create"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
      }
    },
    "/person/{id}/diagnostic/{diagnostic_id}": {
      "delete": {
        "operationId": "DeleteController_delete",
        "summary": "Exclui um objeto DIAGNOSTIC",
        "description": "\n    O que é DIAGNOSTIC?:\n      * DIAGNOSTIC representa o resultado de um exame que pertence ao paciente (person)\n    ",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "O id de person",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "diagnostic_id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "tags": [
          "delete"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
      }
    },
    "/person": {
      "post": {
        "operationId": "CreateController_create",
        "summary": "Cria um objeto PERSON",
        "description": "\nO que é PERSON?:\n* PERSON representa seu cliente (paciente) no em um atendimento\n* PERSON pode ser independente ou ter um responsável legal, basta colocar o ID do PERSON responsável no campo parent_ID\n* O ID de PERSON pode ser informado, caso você integrador queira usar o mesmo ID que já usa em seu sistema, simplificando a integração\n* Se não informar o ID, será gerado um em formato UUID, e deverá ser utilizado para um novo agendamento.\n\nCampos opcionais que precisam ser informados (e ser únicos na base) caso:\n* email: caso o cliente precise receber emails\n* cell_phone: caso o cliente precise receber SMS ou Whatsapp\n    ",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": false,
                "$ref": "#/components/schemas/PersonCreateRequestSchema"
              },
              "examples": {
                "requiredOnly": {
                  "description": "Somente campos obrigatórios. Note que o campo ID segue a regra descrita acima.",
                  "summary": "Somente campos obrigatórios",
                  "value": {
                    "id": "123456",
                    "name": "Roberval Juvencio Lazaroti",
                    "birth_date": "1976-01-23",
                    "email": "roberval@lazaroti.com.br"
                  }
                },
                "full": {
                  "summary": "Todos os campos",
                  "description": "Exemplo com todos os campos possíveis",
                  "value": {
                    "id": "123456",
                    "name": "Roberval Juvencio Lazaroti",
                    "birth_date": "1976-01-23",
                    "email": "roberval@lazaroti.com.br",
                    "cpf": "94819089846",
                    "gender": "M",
                    "cell_phone": "11912345678",
                    "phone": "1112345678",
                    "profession": "Agricultor",
                    "registration": "2312312",
                    "address": {
                      "state": "SP",
                      "city": 3505708,
                      "number": "238",
                      "neighborhood": "Dezoito do Forte",
                      "complement": "4o andar",
                      "street": "Avenida Copacabana",
                      "zip_code": "06472000"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Person successfully created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PersonCreateResponseSchema"
                }
              }
            }
          },
          "400": {
            "description": "Validation Error (field type)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DavHttpExceptionDto"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error (logic)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DavHttpExceptionDto"
                }
              }
            }
          }
        },
        "tags": [
          "create"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
      }
    },
    "/person/{id}": {
      "get": {
        "operationId": "ReadController_get",
        "summary": "Pesquisa um objeto PERSON",
        "description": "* PERSON representa seu cliente (paciente) no em um atendimento.\n",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Person",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PersonReadResponseSchema"
                }
              }
            }
          },
          "204": {
            "description": "Person not found"
          }
        },
        "tags": [
          "read"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
      },
      "put": {
        "operationId": "UpdateController_update",
        "summary": "Substitui os dados do PERSON pelo que for enviado no corpo da requisição",
        "description": "\nO que é PERSON?:\n* PERSON representa seu cliente (paciente) no em um atendimento\n* PERSON pode ser independente ou ter um responsável legal, basta colocar o ID do PERSON responsável no campo parent_ID\n\nCampos opcionais que precisam ser informados caso:\n* email: caso o cliente precise receber emails\n* cell_phone: caso o cliente precise receber SMS ou Whatsapp\n    ",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "O id de person",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PersonUpdateRequestSchema"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PersonUpdateResponseSchema"
                }
              }
            }
          },
          "400": {
            "description": "Validation Error (field type)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DavHttpExceptionDto"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error (logic)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DavHttpExceptionDto"
                }
              }
            }
          }
        },
        "tags": [
          "update"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
      },
      "delete": {
        "operationId": "DeleteController_delete",
        "summary": "Exclui um objeto PERSON",
        "description": "\n* PERSON representa seu cliente (paciente) no em um atendimento.\n* O ID de Person não pode ser reaproveitado. Sua exclusão é LOGICA, ou seja, o registro permanece por histórico das consultas já efetuadas.\n    ",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "O id de person",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "tags": [
          "delete"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
      }
    }
  },
  "info": {
    "title": "Person",
    "description": "Criação e manutenção de clientes (pacientes/atendidos/assistidos)",
    "version": "1.0.0",
    "contact": {}
  },
  "tags": [],
  "servers": [
    {
      "url": "https://api.v2.doutoraovivo.com.br",
      "description": "ambiente de PRODUÇÃO"
    },
    {
      "url": "https://api.v2.hom.doutoraovivo.com.br",
      "description": "ambiente de HOMOLOGAÇÃO"
    }
  ],
  "components": {
    "schemas": {
      "ResultFileSchema": {
        "type": "object",
        "properties": {
          "mime_type": {
            "type": "string",
            "description": "File format (MIME type)",
            "enum": [
              "application/epub+zip",
              "application/gzip",
              "application/json",
              "application/ld+json",
              "application/msword",
              "application/octet-stream",
              "application/ogg",
              "application/pdf",
              "application/rtf",
              "application/vnd.amazon.ebook",
              "application/vnd.apple.installer+xml",
              "application/vnd.mozilla.xul+xml",
              "application/vnd.ms-excel",
              "application/vnd.ms-fontobject",
              "application/vnd.ms-powerpoint",
              "application/vnd.oasis.opendocument.presentation",
              "application/vnd.oasis.opendocument.spreadsheet",
              "application/vnd.oasis.opendocument.text",
              "application/vnd.openxmlformats-officedocument.presentationml.presentation",
              "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
              "application/vnd.rar",
              "application/vnd.visio",
              "application/x-7z-compressed",
              "application/x-abiword",
              "application/x-bzip",
              "application/x-bzip2",
              "application/x-csh",
              "application/x-freearc",
              "application/x-httpd-php",
              "application/x-sh",
              "application/x-shockwave-flash",
              "application/x-tar",
              "application/xhtml+xml",
              "application/xml",
              "application/zip",
              "audio/3gpp",
              "audio/3gpp2",
              "audio/aac",
              "audio/midi audio/x-midi",
              "audio/mpeg",
              "audio/ogg",
              "audio/opus",
              "audio/wav",
              "audio/webm",
              "font/otf",
              "font/ttf",
              "font/woff",
              "font/woff2",
              "image/bmp",
              "image/gif",
              "image/jpeg",
              "image/png",
              "image/svg+xml",
              "image/tiff",
              "image/vnd.microsoft.icon",
              "image/webp",
              "text/calendar",
              "text/css",
              "text/csv",
              "text/html",
              "text/javascript",
              "text/plain",
              "text/xml",
              "video/3gpp",
              "video/3gpp2",
              "video/mp2t",
              "video/mpeg",
              "video/ogg",
              "video/webm",
              "video/x-msvideo"
            ]
          },
          "base_64": {
            "type": "string",
            "format": "byte",
            "description": "Examination result file base64"
          }
        },
        "required": [
          "mime_type",
          "base_64"
        ]
      },
      "DiagnosticCreateRequestSchema": {
        "type": "object",
        "properties": {
          "remetent": {
            "type": "string",
            "description": "Lab that has made the examination"
          },
          "examination_name": {
            "type": "string",
            "description": "Examination name"
          },
          "examination_date": {
            "type": "string",
            "format": "date-time",
            "description": "Examination Date"
          },
          "result_description": {
            "type": "string",
            "description": "Examination result description"
          },
          "result_file": {
            "description": "Endereço",
            "additionalProperties": false,
            "allOf": [
              {
                "$ref": "#/components/schemas/ResultFileSchema"
              }
            ]
          }
        },
        "required": [
          "remetent",
          "examination_name",
          "examination_date",
          "result_description"
        ]
      },
      "i18nMessageConfig": {
        "type": "object",
        "properties": {}
      },
      "DavHttpExceptionDto": {
        "type": "object",
        "properties": {
          "code": {
            "type": "number",
            "description": "HTTP Response Code"
          },
          "message": {
            "type": "string",
            "description": "Error Message"
          },
          "i18n": {
            "description": "For use with Frontend only",
            "allOf": [
              {
                "$ref": "#/components/schemas/i18nMessageConfig"
              }
            ]
          },
          "detail": {
            "description": "Individual Messages",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "trace": {
            "type": "string",
            "description": "Trace ID - pass it to DaV support"
          }
        },
        "required": [
          "code",
          "message",
          "trace"
        ]
      },
      "AddressSchema": {
        "type": "object",
        "properties": {
          "zip_code": {
            "type": "string",
            "pattern": "^\\d{5}\\d{3}$",
            "description": "CEP (Codigo de Enderecamento Postal)",
            "example": "06010210"
          },
          "street": {
            "type": "string",
            "description": "Logradouro",
            "example": "Avenida Copacabana"
          },
          "number": {
            "type": "string",
            "description": "Número do recinto",
            "example": "238"
          },
          "complement": {
            "type": "string",
            "description": "Complemento do Endereço",
            "example": "4o andar"
          },
          "neighborhood": {
            "type": "string",
            "description": "Bairro",
            "example": "Dezoito do Forte"
          },
          "city": {
            "type": "number",
            "description": "Código do município do IBGE (https://www.ibge.gov.br/explica/codigos-dos-municipios.php)",
            "example": 3505708
          },
          "state": {
            "type": "string",
            "description": "Estado (UF)",
            "example": "SP",
            "enum": [
              "AC",
              "AL",
              "AP",
              "AM",
              "BA",
              "CE",
              "DF",
              "ES",
              "GO",
              "MA",
              "MT",
              "MS",
              "MG",
              "PR",
              "PB",
              "PA",
              "PE",
              "PI",
              "RN",
              "RS",
              "RJ",
              "RO",
              "RR",
              "SC",
              "SE",
              "SP",
              "TO"
            ]
          }
        },
        "required": [
          "zip_code",
          "street",
          "number",
          "neighborhood",
          "city",
          "state"
        ]
      },
      "PersonCreateRequestSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique Identificator"
          },
          "parent_id": {
            "type": "string",
            "description": "Id of this person legal responsible"
          },
          "name": {
            "type": "string",
            "description": "Name"
          },
          "cpf": {
            "type": "string",
            "description": "CPF",
            "example": "94819089846",
            "pattern": "^\\d{3}\\d{3}\\d{3}\\d{2}$"
          },
          "registration": {
            "type": "string",
            "description": "Special Field like registration ID or social service ID"
          },
          "birth_date": {
            "type": "string",
            "format": "date",
            "description": "Birth Date"
          },
          "gender": {
            "type": "string",
            "description": "Gender",
            "enum": [
              "F",
              "M"
            ]
          },
          "phone": {
            "type": "string",
            "description": "Phone Number (if applicable)",
            "example": "1112345678",
            "pattern": "^\\d{2}\\d{4}\\d{4}$"
          },
          "cell_phone": {
            "type": "string",
            "description": "Phone Number (if applicable)",
            "example": "11912345678",
            "pattern": "^\\d{2}\\d{5}\\d{4}$"
          },
          "profession": {
            "type": "string",
            "maxLength": 100,
            "example": "Accountant"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "person@example.dav.med.br"
          },
          "address": {
            "description": "Endereço",
            "additionalProperties": false,
            "allOf": [
              {
                "$ref": "#/components/schemas/AddressSchema"
              }
            ]
          }
        },
        "required": [
          "name",
          "birth_date",
          "email"
        ]
      },
      "PersonCreateResponseSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique Identificator"
          }
        }
      },
      "PersonReadResponseSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique Identificator"
          },
          "parent_id": {
            "type": "string",
            "description": "Id of this person legal responsible"
          },
          "name": {
            "type": "string",
            "description": "Name"
          },
          "cpf": {
            "type": "string",
            "description": "CPF",
            "example": "94819089846",
            "pattern": "^\\d{3}\\d{3}\\d{3}\\d{2}$"
          },
          "registration": {
            "type": "string",
            "description": "Special Field like registration ID or social service ID"
          },
          "birth_date": {
            "type": "string",
            "format": "date",
            "description": "Birth Date"
          },
          "gender": {
            "type": "string",
            "description": "Gender",
            "enum": [
              "F",
              "M"
            ]
          },
          "phone": {
            "type": "string",
            "description": "Phone Number (if applicable)",
            "example": "1112345678",
            "pattern": "^\\d{2}\\d{4}\\d{4}$"
          },
          "cell_phone": {
            "type": "string",
            "description": "Phone Number (if applicable)",
            "example": "11912345678",
            "pattern": "^\\d{2}\\d{5}\\d{4}$"
          },
          "profession": {
            "type": "string",
            "maxLength": 100,
            "example": "Accountant"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "person@example.dav.med.br"
          },
          "address": {
            "description": "Endereço",
            "additionalProperties": false,
            "allOf": [
              {
                "$ref": "#/components/schemas/AddressSchema"
              }
            ]
          }
        },
        "required": [
          "name",
          "birth_date",
          "email"
        ]
      },
      "PersonUpdateRequestSchema": {
        "type": "object",
        "properties": {
          "parent_id": {
            "type": "string",
            "description": "Id of this person legal responsible"
          },
          "name": {
            "type": "string",
            "description": "Name"
          },
          "cpf": {
            "type": "string",
            "description": "CPF",
            "example": "94819089846",
            "pattern": "^\\d{3}\\d{3}\\d{3}\\d{2}$"
          },
          "registration": {
            "type": "string",
            "description": "Special Field like registration ID or social service ID"
          },
          "birth_date": {
            "type": "string",
            "format": "date",
            "description": "Birth Date"
          },
          "gender": {
            "type": "string",
            "description": "Gender",
            "enum": [
              "F",
              "M"
            ]
          },
          "phone": {
            "type": "string",
            "description": "Phone Number (if applicable)",
            "example": "1112345678",
            "pattern": "^\\d{2}\\d{4}\\d{4}$"
          },
          "cell_phone": {
            "type": "string",
            "description": "Phone Number (if applicable)",
            "example": "11912345678",
            "pattern": "^\\d{2}\\d{5}\\d{4}$"
          },
          "profession": {
            "type": "string",
            "maxLength": 100,
            "example": "Accountant"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "person@example.dav.med.br"
          },
          "address": {
            "description": "Endereço",
            "additionalProperties": false,
            "allOf": [
              {
                "$ref": "#/components/schemas/AddressSchema"
              }
            ]
          }
        },
        "required": [
          "name",
          "birth_date",
          "email"
        ]
      },
      "PersonUpdateResponseSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique Identificator"
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ]
}
